[package]
name = "clap-sample-rs"
version = "0.1.0"
authors = ["4832cl0n"]
edition = "2018"
description = "Clap Example CLI ref toml"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"